name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install --use-feature=2020-resolver -r requirements.txt -r requirements-dev.txt

      - name: Check Formatting
        run: |
          . venv/bin/activate
          inv lint_black
      - name: Check Linting
        run: |
          . venv/bin/activate
          inv lint_pylint
      - name: Check Types
        run: |
          . venv/bin/activate
          inv lint_mypy
      - name: Test
        run: |
          . venv/bin/activate
          inv test
